name: Deploy on github pages

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn Install
      run: yarn install --frozen-lockfile --network-timeout 100000
    - name: Build Vue
      run: yarn build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        # Build directory to deploy
        build_dir: dist
        # Git branch where assets will be deployed
        target_branch: gh-pages
        # Allow Jekyll to build your site
        jekyll: false # default is true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
